on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Run Shellcheck
      env:
        REPORT_ONLY: true
        SHOW_ERRORS: true
      run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)